### ISSUE TITLE
error issue

### ISSUE THREAD

**Issue by nvyao** [davidism/mcafee-epo#2]
```pytb
Traceback (most recent call last):
  File "E:/py_workstation/common/programe/office_scan/McAfee/mcafee_py/mcafee_epo_1.py", line 7, in <module>
    systems = client('system.find', 'zhangsan')
  File "C:\Python27\lib\site-packages\mcafee_epo.py", line 120, in __call__
    return self._request(name, params=params, files=files)
  File "C:\Python27\lib\site-packages\mcafee_epo.py", line 69, in _request
    self._get_token(_skip=name == "core.getSecurityToken"),
  File "C:\Python27\lib\site-packages\mcafee_epo.py", line 49, in _get_token
    self._token = self._request("core.getSecurityToken")
  File "C:\Python27\lib\site-packages\mcafee_epo.py", line 77, in _request
    r = self._session.get(url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.25.160', port=8443): Max retries exceeded with url: /remote/core.getSecurityToken?%3Aoutput=json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

**Comment by davidism** [comment]
Duplicate of #1
